### ISSUE TITLE
Update all Custom Plugins / compile against Java 16 & MC 1.17

### ISSUE THREAD

**Issue by sleepylessons** [sleepylessons/NetherAnarchy#19]
## Maintenance Task to be Completed:
We need to update all of our custom plugins to ensure maximum compatibility with not only Java 16 (we're currently on 11) but also with the latest update to MC 1.17 when Spigot/Paper have updated.

## Sub-task listing; checkbox list of steps to complete

Update all the following custom plugins:
- [ ] NetherAnarchySuffix
- [ ] NetherAnarchyFarms
- [ ] NetherAnarchyLoot
- [ ] NetherAnarchyNick** (not yet implemented, non-blocking)
- [ ] NetherAnarchyParty
- [ ] NetherAnarchyRename
- [ ] NetherAnarchySecure
- [ ] NetherAnarchyTravel
- [ ] NetherAnarchyUtility
- [ ] NetherAnarchyVote

Check compatibility/update following non-custom plugins:
- [ ] AntiBookBan
- [ ] AntiTNTDupe
- [ ] BotSentry
- [ ] BuyCraft
- [ ] ChatSentintel
- [ ] ConditionalCommands
- [ ] DeathMessagesPrime
- [ ] Essentials X & EssentialsX Chat (todo: remove these and replace with NetherAnarchyNick as well)
- [ ] FarmLimiter
- [ ] LuckPerms
- [ ] NoCheatPlus
- [ ] ProtocolLib
- [ ] RandomSpawnPlus
- [ ] RedstoneClockDetector (non-blocking, can potentially be removed)
- [ ] Spark
- [ ] TCPShield
- [ ] Vault
- [ ] ViaVersion & ViaBackwards
- [ ] WorldEdit (non-blocking, can be removed if necessary)

**Comment by jakepriddle** [comment]
Please let me know how you solve the ncp problem. I know some 1.17 blocks flag ncp for survival fly.

**Comment by sleepylessons** [comment]
@jakepriddle kind of out of my hands, I don't plan on doing a personal rework of NCP. You can refer to the repo here for updates related to 1.17:

https://github.com/Updated-NoCheatPlus/NoCheatPlus/

**Comment by jakepriddle** [comment]
> @jakepriddle kind of out of my hands, I don't plan on doing a personal rework of NCP for 1.17. We could potentially be dealing with some false positives for a while until they work it out. You can refer to the repo here for updates related to 1.17:
> 
> https://github.com/Updated-NoCheatPlus/NoCheatPlus/

Yah I was running into problem with amethyst buds. The current solution is just to whitelist them in the config.
